### ISSUE TITLE
sync times

### ISSUE THREAD

**Issue by bjackson** [TakefiveInteractive/ece391ForMac#2]
Should sync sync all files in the work directory? It takes more than an hour on my machine. Wouldn't it just be better to sync qcow files?

**Comment by Tedko** [comment]
files created on your ews is not in the qcow. We're finding a way to reduce the time

**Comment by bjackson** [comment]
Couldn't those just be synced through SVN?

On Mon, Sep 7, 2015 at 10:11 PM -0700, "Han" notifications@github.com wrote:

files created on your ews is not in the qcow. We're finding a way to reduce the time

**Comment by tengyifei** [comment]
`unison` spends most of its time going over the entire linux kernel source code, which is NOT checked in to source control. I'm not sure if we are modifying the kernel in the future (probably in MP1), so there's no better alternative I could see.

**Comment by markzyu** [comment]
I believe there is no need to sync "source/" and "repo/" because when we operate on the files in those folders, the operation is always directly acting on the ews server. (Even if we synced "source" and "repo" to our local machine, we will have to modify the scripts in Linux virtual machine. Otherwise, no one will be modifying the files on the local machine.)

**Comment by tengyifei** [comment]
We are not gonna act directly on the two network-shared locations since
that defeats the whole purpose of a local setup. Instead, we mirror the
network content onto our local disks and only synchronize them once in a
while - when you're in the lab.
